apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: http
    port: 5173
    targetPort: 0
  selector:
    app: frontend
  type: ClusterIP