apiVersion: v1
data:
  NODE_ENV: development
  services__apiservice__http__0: http://apiservice:8080
  services__apiservice__tcp__0: apiservice:8000
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: frontend
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: frontend
  name: frontend