services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    restart: unless-stopped
  cache:
    container_name: "cache"
    image: "redis:7.2"
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass 3TW5v!TvdlSppu8R1nNSnU
    environment:
      REDIS_PASSWORD: "3TW5v!TvdlSppu8R1nNSnU"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "cache"
    restart: unless-stopped
  postgres:
    container_name: "postgres"
    image: "docker.io/library/postgres:17.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YyhiMGrlOzbluFoyBfjnzZ"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "postgres"
    ports:
    - target: 5432
      published: 5432
    restart: unless-stopped
  apiservice:
    container_name: "apiservice"
    image: "apiservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__cache: "cache:6379,password=3TW5v!TvdlSppu8R1nNSnU"
      ConnectionStrings__postgres: "Host=postgres;Port=5432;Username=postgres;Password=YyhiMGrlOzbluFoyBfjnzZ"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "apiservice"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    - target: 8000
      published: 10002
    restart: unless-stopped
  frontend:
    container_name: "frontend"
    image: "frontend:latest"
    environment:
      NODE_ENV: "development"
      services__apiservice__http__0: "http://apiservice:8080"
      services__apiservice__tcp__0: "apiservice:8000"
      BACKEND_URL: "http://apiservice:8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "frontend"
    ports:
    - target: 5173
      published: 5173
    restart: unless-stopped
