# Run when commits are pushed to master
on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - master

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30  # Prevent hanging jobs on self-hosted runners
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      # Ensure clean environment for self-hosted runners
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true  # Ensure clean checkout on self-hosted runners

      # Check if tools are already installed (common on self-hosted runners)
      - name: Check existing installations
        shell: bash
        run: |
          echo "Checking existing installations..."
          
          # Check .NET
          if command -v dotnet &> /dev/null; then
            dotnetVersion=$(dotnet --version 2>/dev/null || echo "unknown")
            echo "✅ .NET already installed: $dotnetVersion"
            echo "DOTNET_INSTALLED=true" >> $GITHUB_ENV
          else
            echo "❌ .NET not found"
            echo "DOTNET_INSTALLED=false" >> $GITHUB_ENV
          fi
          
          # Check azd
          if command -v azd &> /dev/null; then
            azdVersion=$(azd version 2>/dev/null || echo "unknown")
            echo "✅ azd already installed: $azdVersion"
            echo "AZD_INSTALLED=true" >> $GITHUB_ENV
          else
            echo "❌ azd not found"
            echo "AZD_INSTALLED=false" >> $GITHUB_ENV
          fi

      - name: Setup .NET
        if: env.DOTNET_INSTALLED == 'false'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.x.x
            9.x.x

      - name: Install azd
        if: env.AZD_INSTALLED == 'false'
        uses: Azure/setup-azd@v2

      # Install/Update .NET Aspire workload (always run to ensure latest)
      - name: Install .NET Aspire workload
        shell: bash
        run: |
          echo "Installing/Updating .NET Aspire workload..."
          dotnet workload install aspire --skip-sign-check
          dotnet workload list

      # Clean previous builds (important for self-hosted runners)
      - name: Clean previous builds
        shell: bash
        run: |
          echo "Cleaning previous builds..."
          
          # Find and remove bin/obj directories
          if [ -d "./src" ]; then
            find ./src -type d \( -name "bin" -o -name "obj" \) -exec rm -rf {} + 2>/dev/null || true
            echo "Removed bin/obj directories"
          fi
          
          # Clean NuGet cache if needed
          dotnet nuget locals all --clear

      # Restore and build to catch issues early
      - name: Restore dependencies
        run: dotnet restore --verbosity normal

      - name: Build solution
        run: dotnet build --no-restore --configuration Release --verbosity normal

      # Login to Azure
      - name: Log in with Azure (Federated Credentials)
        shell: bash
        run: |
          echo "Logging in to Azure..."
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"
          
          # Verify login
          azd auth login --check

      # Provision infrastructure
      - name: Provision Infrastructure
        shell: bash
        run: |
          echo "Provisioning Azure infrastructure..."
          azd provision --no-prompt
        env:
          AZURE_POSTGRES_PASSWORD: ${{ secrets.AZURE_POSTGRES_PASSWORD }}
          AZURE_CACHE_PASSWORD: ${{ secrets.AZURE_CACHE_PASSWORD }}

      # Deploy application
      - name: Deploy Application
        shell: bash
        run: |
          echo "Deploying application..."
          azd deploy --no-prompt
        env:
          AZURE_POSTGRES_PASSWORD: ${{ secrets.AZURE_POSTGRES_PASSWORD }}
          AZURE_CACHE_PASSWORD: ${{ secrets.AZURE_CACHE_PASSWORD }}

      # Cleanup (important for self-hosted runners to prevent state issues)
      - name: Cleanup
        if: always()
        shell: bash
        run: |
          echo "Performing cleanup..."
          
          # Stop any running dotnet processes
          pkill -f dotnet || true
          
          # Clean Docker containers and images if Docker is available
          if command -v docker &> /dev/null; then
            docker system prune -f --volumes 2>/dev/null || true
            echo "✅ Docker cleanup completed"
          else
            echo "ℹ️ Docker not available or cleanup not needed"
          fi
          
          echo "Cleanup completed"
